package com.easynet.util;

public class ProcedureConstantName {
	public static String PROC_POST_LOGIN = "PACK_ADMINP_AUTH_MSERVICE.PROC_POST_LOGIN";
	// public static String PROC_AUTH_LOGIN = "PROC_VALIDATE_USER_LOGIN";
	public static String PROC_AUTH_LOGIN = "PACK_USER_LOGIN.PROC_VALIDATE_USER_LOGIN"; /*
																						 * change made by pratiksha into
																						 * proc as per discuson with
																						 * aditya sir
																						 */
	public static String PROC_RESENT_OTP = "PROC_RESENT_OTP";
//	public static String PROC_VERIFY_LOGIN_OTP_BIO = "PROC_VERIFY_LOGIN_OTP_BIO";
	public static String PROC_LOGOUT_USER = "PACK_USER_LOGIN.PROC_LOGOUT_USER";
//	public static String PROC_UPD_NEW_PWD = "PROC_UPD_NEW_PWD";
	public static String PROC_CHECK_FORGOTPWD_OTP = "PACK_USER_LOGIN.PROC_CHECK_FORGOTPWD_OTP";
	public static String PROC_SEND_FORGOTPWD_OTP = " PACK_USER_LOGIN.PROC_SEND_FORGOTPWD_OTP";
	// public static String PROC_VERIFY_LOGIN_OTP_BIO = "PROC_VERIFY_LOGIN_OTP_BIO";
	public static String PROC_VERIFY_LOGIN_OTP_BIO = "PACK_USER_LOGIN.PROC_VERIFY_LOGIN_OTP_BIO";/*
																									 * change made by
																									 * pratiksha into
																									 * proc as per
																									 * discuson with
																									 * aditya sir
																									 */
//	public static String PROC_LOGOUT_USER = "PROC_LOGOUT_USER";
	// public static String PROC_UPD_NEW_PWD = "PROC_UPD_NEW_PWD";
	public static String PROC_UPD_PWD = "PACK_USER_LOGIN.PROC_UPD_PWD";/*
																		 * change made by pratiksha into proc as per
																		 * discuson with aditya sir
																		 */
	public static String PROC_UPDATE_TOTP_AUTH = "PACK_TOTP_AUTH.PROC_UPDATE_TOTP_AUTH";
	public static String PROC_VERIFY_UPD_TOTP_AUTH = "PACK_USER_LOGIN.PROC_VERIFY_UPD_TOTP_AUTH";
	public static String PROC_GET_CUST_ID_DATA = "PACK_ACCT_MST.PROC_GET_CUST_ID_DATA";
	public static String PROC_GET_ACCT_REQ_LATEST_DATA = "PACK_ACCT_MST.PROC_GET_ACCT_REQ_LATEST_DATA";
	public static String PROC_GET_ACCT_NM = "PACK_CTS_OUTWARD_Clearing.PROC_GET_ACCT_NM";
	public static String ACCTINQUIRY = "PROC_ACCT_INQUIRY_SEARCH";
	public static String PROC_ACCT_VALIDATION = "PACK_ACCT_MST.PROC_ACCT_VALIDATION";
	public static String PR_DUPLICATE_CHECK = "EASY_BANK.PR_DUPLICATE_CHECK";
	public static String ACCOUNTDTL = "EASY_BANK.PACK_STMT_OF_ACCT.PROC_STMT_OF_ACCT_DTL";
	public static String ACCTTRAN = "EASY_BANK.PACK_STMT_OF_ACCT.PROC_STMT_OF_ACCT_TRAN";
	public static String BRANCHDTL = "EASY_BANK.PACK_STMT_OF_ACCT.PROC_STMT_OF_ACCT_BRANCH_DTL";
	public static String ACCTSUM = "EASY_BANK.PACK_STMT_OF_ACCT.PROC_STMT_OF_ACCT_SUMMARY";
	public static String META_DATA = "EASY_BANK.PACK_STMT_OF_ACCT.PROC_STMT_OF_ACCT_METADATA";
	public static String NOTES = "EASY_BANK.PACK_STMT_OF_ACCT.PROC_STMT_OF_ACCT_NOTES";
	public static String PROC_AC_CLOSE_VALIDATION = "PACK_ACCT_MST.PROC_AC_CLOSE_VALIDATION";
	public static String PROC_CHECK_PASSWORD = "PACK_SECURITY_USER .PROC_CHECK_PASSWORD";
	public static String PROC_GET_OTP = "EASY_BANK.PACK_OTP.PROC_GET_OTP";
	public static String PROC_CHECK_OTP = "EASY_BANK.PACK_OTP.PROC_CHECK_OTP";
	public static String PROC_VALIDATE_ACCT_CUST_ID = "PACK_ATM_REG.PROC_VALIDATE_ACCT_CUST_ID";
	public static String PROC_VALIDATION_SAVE = "PACK_RTGS.PROC_VALIDATION_SAVE";
	public static String PROC_CHECK_USER_NM = "PACK_SECURITY_USER.PROC_CHECK_USER_NM";
	public static String PROC_INS_DELETE_EXCEPTION = "PROC_INS_DELETE_EXCEPTION";
	public static String PROC_GET_ACCT_DATA = "PACK_RTGS.PROC_GET_ACCT_DATA";
	public static String PROC_AMOUNT_VALIDATION = "PACK_RTGS.PROC_AMOUNT_VALIDATION";
	public static String PROC_BENEFICIARY_VALIDATION = "PACK_RTGS.PROC_BENEFICIARY_VALIDATION";
	public static String PROC_GET_VALID_CHQ_NO = "PACK_CHEQUE_BOOK_ISSUE.PROC_GET_VALID_CHQ_NO";
	public static String PROC_GET_IFSC_DETAILS = "PACK_RTGS.PROC_GET_IFSC_DETAILS";
	public static String PROC_GET_RTGS_CHARGES = "PACK_RTGS.PROC_GET_RTGS_CHARGES";
	public static String PROC_FILE_IMPORT_VALIDATION = "PACK_POSITIVE_PAY.PROC_FILE_IMPORT_VALIDATION";
	public static String PROC_DELETE_CASH_TRN = "PACK_TELLER_TRANSACTION.PROC_DELETE_CASH_TRN";
	public static String PROC_UPD_FORGOT_PWD = "PACK_USER_LOGIN.PROC_UPD_FORGOT_PWD";
	public static String PROC_ISSUE_CHEQUE_BOOK = "EASY_BANK.PROC_ISSUE_CHEQUE_BOOK";
	public static String PROC_GEN_DUAL_CONF = "PROC_GEN_DUAL_CONF";
	public static String PR_DUAL_CONF_HISTORY = "EASY_BANK.PR_DUAL_CONF_HISTORY";
	public static String PACK_GST_OUTWARD_PROC_GET_ACCT_DATA = "PACK_GST_OUTWARD.PROC_GET_ACCT_DATA";
	public static String PROC_GET_PAYSLIP_ISSUE_CHARGE = "PACK_PAYSLIP.PROC_GET_PAYSLIP_ISSUE_CHARGE";
	public static String PACK_PAYSLIP_PROC_VALIDATION_SAVE = "PACK_PAYSLIP.PROC_VALIDATION_SAVE";
	public static String PROC_CONFIRM_REC_PAYMENT = "PACK_RECURRING_PAYMENT.PROC_CONFIRM_REC_PAYMENT";
	public static String PROC_SIGN_PHOTO_VIEW = "PROC_SIGN_PHOTO_VIEW";
	public static String PROC_DELETE_SI_EXECUTED = "EASY_BANK.PROC_DELETE_SI_EXECUTED";
	public static String PROC_GET_CR_ACCT_DATA = "PACK_STANDING_INSTRUCTION.PROC_GET_CR_ACCT_DATA";
	public static String PROC_DEL_SI_EXE_REC = "PACK_STANDING_INSTRUCTION.PROC_DEL_SI_EXE_REC";
	public static String PROC_GET_DR_ACCT_DATA = "PACK_STANDING_INSTRUCTION.PROC_GET_DR_ACCT_DATA";
	public static String PROC_GET_SI_CHARGE = "PACK_STANDING_INSTRUCTION.PROC_GET_SI_CHARGE";
	public static String PROC_INS_REC_PAYMENT = "PACK_RECURRING_PAYMENT.PROC_INS_REC_PAYMENT";
	public static String PROC_GEN_ENTRY = "PACK_GEN_OTH_MODULE_DD_NEFT.PROC_GEN_ENTRY";
	public static String PROC_INS_GSTOUT_ENTRY = "PACK_GST_OUTWARD.PROC_INS_GSTOUT_ENTRY";
	public static String PROC_VALIDATE_CITIZEN_ID = "PACK_ATM_REG.PROC_VALIDATE_CITIZEN_ID";
	public static String PROC_GET_CUST_REQ_LATEST_DATA = "PACK_UPD_CUST_MST.PROC_GET_CUST_REQ_LATEST_DATA";
	public static String PROC_GET_NRI_REQ_LATEST_DATA = "PACK_UPD_CUST_MST.PROC_GET_NRI_REQ_LATEST_DATA";
	public static String PROC_GET_CUST_MORE_LATEST_DATA = "PACK_UPD_CUST_MST.PROC_GET_CUST_MORE_LATEST_DATA";
	public static String PROC_RETRIEVE_DATA = "PACK_ACCT_MST.PROC_RETRIEVE_DATA";
	public static String PROC_RETRIEVE_CUST_DATA = "PACK_UPD_CUST_MST.PROC_RETRIEVE_CUST_DATA";
	public static String PROC_VALIDATE_REGEN = "PACK_LOAN_SCHEDULE.PROC_VALIDATE_REGEN";
	public static String PROC_REGEN_LOAN_SCHEDULE = "EASY_BANK.PROC_REGEN_LOAN_SCHEDULE";
	public static String PROC_REC_CALCULATOR = "PACK_RECURRING_PAYMENT.PROC_REC_CALCULATOR";
	public static String PROC_GET_UPD_RATE_DTL = "PACK_LOAN_SCHEDULE.PROC_GET_UPD_RATE_DTL";
	public static String PROC_RETRIEVE_HDR_DATA = "PACK_ATM_REG.PROC_RETRIEVE_HDR_DATA";
	public static String PROC_VALIDATE_SAVE = "PACK_ATM_REG.PROC_VALIDATE_SAVE";
	public static String PROC_VALIDATE_CARD_STATUS = "PACK_ATM_REG.PROC_VALIDATE_CARD_STATUS";
	public static String INSURANCE_PROC_VALIDATION_SAVE = "PACK_INSURANCE.PROC_VALIDATION_SAVE";
	public static String PROC_FD_DTL_DISP_BFD = "PACK_LIMIT.PROC_FD_DTL_DISP_BFD";
	public static String PROC_FD_DTL_DISP_BRD = "PACK_LIMIT.PROC_FD_DTL_DISP_BRD";
	public static String PROC_FD_DTL_BTN = "PACK_LIMIT.PROC_FD_DTL_BTN";
	public static String PROC_VALIDATE_AC = "PACK_LIMIT.PROC_VALIDATE_AC";
	public static String PROC_GET_LIMIT_RATE = "PACK_LIMIT.PROC_GET_LIMIT_RATE";
	public static String PROC_VALIDATION_DELETE = "PACK_LIMIT.PROC_VALIDATION_DELETE";
	public static String PROC_GET_FD_PARA = "PACK_FD_PROCESS.PROC_GET_FD_PARA";
	public static String VALIDATE_ACCOUNT = "PACK_FD_PROCESS.PROC_GET_ACCT_DATA";
	public static String PACK_LOAN_SCHEDULE_PROC_GET_ACCT_DATA = "PACK_LOAN_SCHEDULE.PROC_GET_ACCT_DATA";
	public static String PACK_LOAN_SCHEDULE_PROC_LOAN_RESCHEDULE_PROCEED = "PACK_LOAN_SCHEDULE.PROC_LOAN_RESCHEDULE_PROCEED";
	public static String PACK_LOAN_SCHEDULE_PROC_LOAN_RESCHEDULE_SAVE = "PACK_LOAN_SCHEDULE.PROC_LOAN_RESCHEDULE_SAVE";
	public static String PROC_VALIDATE_DEPOSIT_TRN = "PACK_FD_PROCESS.PROC_VALIDATE_DEPOSIT_TRN";
	public static String PROC_GEN_DEPOSIT_TRN = "PACK_FD_PROCESS.PROC_GEN_DEPOSIT_TRN";
	public static String PROC_DAILY_TRN_IMPORT = "EASY_BANK.PROC_DAILY_TRN_IMPORT";
	public static String PROC_CASH_EXCHANGE_TRN_INS = "PACK_TELLER_TRANSACTION.PROC_CASH_EXCHANGE_TRN_INS";
	public static String PROC_EMI_CALCULATE = "PACK_EMI_CALCULATOR.PROC_EMI_CALCULATE";
	public static String PROC_VALIDATE_UPD = "PACK_FD_PROCESS.PROC_VALIDATE_UPD";
	public static String PROC_ENC_APPL_SESSION_TRAN = "EASY_BANK.PROC_ENC_APPL_SESSION_TRAN";
	public static String PROC_GET_REPORT_HEADER = "PROC_GET_REPORT_HEADER";
	public static String PROC_RELEASE_CASH_TRN = "PACK_TELLER_TRANSACTION.PROC_RELEASE_CASH_TRN";
	public static String PROC_GEN_PAYMENT_TRN = "PACK_FD_PROCESS.PROC_GEN_PAYMENT_TRN";
	public static String PROC_DELETE_TRN = "PACK_FD_PROCESS.PROC_DELETE_TRN";
	public static String PR_ACT_AUDIT_TRAIL_RPT = "EASY_BANK.PR_ACT_AUDIT_TRAIL_RPT";
	public static String PROC_LOAN_RESCHEDULE_CONF = "EASY_BANK.PROC_LOAN_RESCHEDULE_CONF";
	public static String PROC_UPD_LIEN = "PACK_FD_PROCESS.PROC_UPD_LIEN";
	public static String PACK_FD_PROCESS_PROC_CONFIRM_TRN = "PACK_FD_PROCESS.PROC_CONFIRM_TRN";
	public static String PROC_CHECK_PAYSLIP_DELETE = "PACK_PAYSLIP.PROC_CHECK_PAYSLIP_DELETE";
	public static String PROC_CALC_ACCT_INT = "PACK_DAILY_TRN_F1.PROC_CALC_ACCT_INT";
	public static String PROC_APPLY_ACCT_INT = "PACK_DAILY_TRN_F1.PROC_APPLY_ACCT_INT";
	public static String PROC_DELETE_DAILY_TRN = "EASY_BANK.PROC_DELETE_DAILY_TRN";
	public static String PROC_UPD_PHOTO_SIGN = "PACK_ACCT_MST.PROC_UPD_PHOTO_SIGN";
	public static String PROC_CONF_PHOTO_SIGN = "PACK_ACCT_MST.PROC_CONF_PHOTO_SIGN";
	public static String PROC_CUST_DATA_VALIDATE = "PACK_UPD_CUST_MST.PROC_CUST_DATA_VALIDATE";
	public static String PR_CUST_ACCT_INFO = "EASY_BANK.PR_CUST_ACCT_INFO";
	public static String PROC_UPD_FREEZE_STATUS = "PROC_UPD_FREEZE_STATUS";
	public static String PROC_CONF_REJECT_FROM_HO = "PACK_RTGS.PROC_CONF_REJECT_FROM_HO";
	public static String TRANDETAIL = "PACK_TELLER_TRANSACTION.proc_get_today_tran_dtl";
}
